spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti-test?serverTimezone=Asia/Shanghai&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 4869426
    driver-class-name: com.mysql.cj.jdbc.Driver
  activiti:
    check-process-definitions: false
    database-schema-update: 'false'
  thymeleaf:
    mode: LEGACYHTML5
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        format_sql: true
#        use_sql_comments: true

server:
  port: 9000
  servlet:
    context-path: /activiti-example
